[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"
via-ir = true
optimizer = true
optimizer_runs = 200
gas_reports = ["ESGID", "Performance"]

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
]